### ISSUE TITLE
Remove Outline When Buttons Clicked

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#1369]
When buttons are clicked on the website the default blue outline appears , I find it quite annoying so could you remove , here is how you could do it:
``
button:focus{
outline:none;
}
``

**Comment by AadityaMunjal** [comment]
I'm working on it

**Comment by HonbraDev** [comment]
The outline is for users navigating with their keyboards. I would not remove it.

**Comment by f1shy-dev** [comment]
Possibly we add focus classes that could change button colours/custom rounded outline instead? Making it look better instead of removing it is a better solution in my opinion.

>  here is how you could do it: `button:focus{ outline:none; }`

Also, DogeHouse uses TailwindCSS so we would do `button {@apply focus:outline-none}` to apply it to all buttons, or `<button className="focus:outline-none ..."` for a single button instead.

**Comment by AadityaMunjal** [comment]
> Also, DogeHouse uses TailwindCSS so we would do `button {@apply focus:outline-none}` to apply it to all buttons, or `<button className="focus:outline-none ..."` for a single button instead.

I did that

**Comment by benawad** [comment]
https://www.a11yproject.com/posts/2013-01-25-never-remove-css-outlines/

**Comment by vi241** [comment]
@benawad you can add better looking custom outlines or on focus background ...
