### ISSUE TITLE
Sound on Ubuntu as soon as I join a room

### ISSUE THREAD

**Issue by Complexia** [benawad/dogehouse#1958]
**Describe the bug**
As soon as I join any room, the system sound is turned off, as though I muted it, although it does't appear to be so. Nor dogehouse room nor any other system sound i.e. on another tab works, and as soon as I leave the room, the sound is back on. Started happening today. Problem on both, headphones and speakers.

**To Reproduce**
1. Join room
2. Check if system sound is working

**What device are you on?**
Running on Ubuntu 20.04.2 LTS

I've tried it over a period of a few hours, and the bug seems to persist, rendering dogehouse unable to use. Tried restarting my system and everything, no dice.

**Comment by ajhalili2006** [comment]
Hi, @Complexia! Did you installed the desktop client through `snap`? If yes, there's an PR that currently on review at #1947 regarding adding `audio-record` interface (by default, you might need to manually connect the interface with `snap connect dogehouse:audio-record` on an terminal because as [per the documentation on supported interfaces, it is not autoconnected on install](https://snapcraft.io/docs/supported-interfaces) and may [requires human review in the Snapcraft Forums](https://forum.snapcraft.io/t/process-for-aliases-auto-connections-and-tracks/455)).

**Comment by Complexia** [comment]
Hey @AndreiJirohHaliliDev2006, I was using the web app.

**Comment by ajhalili2006** [comment]
> Hey @AndreiJirohHaliliDev2006, I was using the web app.

@Complexia Something like browser interaction required to play audio. Can you get the console logs from your browser's DevTools? Also what browser are you using?

**Comment by Complexia** [comment]
![beforeJoinRoom](https://user-images.githubusercontent.com/26061194/114338712-fdc6dc80-9b96-11eb-850e-aade3f1824ae.png)

Here's the log before joining a room, all system sound is on and working fine.

![afterJoiningRoom](https://user-images.githubusercontent.com/26061194/114338745-12a37000-9b97-11eb-9741-630068ce7289.png)

Here's the log of after joining a room, all system sound is gone.

![afterLeavingRoom](https://user-images.githubusercontent.com/26061194/114338810-336bc580-9b97-11eb-8043-c8d82da03a56.png)

Here's after leaving a room, all sound is still gone. I have to actually close the tab to get it back to working.

Browser is Google Chrome
