### ISSUE TITLE
Copyright?

### ISSUE THREAD

**Issue by IntegraterGithub** [benawad/dogehouse#2215]
Will you put copyright on dogehouse?

**Comment by TheOtterlord** [comment]
What do you mean exactly by copyright?

Do you mean the code? the brand? or something else?

**Comment by dk-raw** [comment]
What are you referring  as "copyright"?

**Comment by jobveldhuis** [comment]
The closest to copyright you will probably find in this repository is the [license](https://github.com/benawad/dogehouse/blob/staging/LICENSE), which is an [MIT License](https://en.wikipedia.org/wiki/MIT_License) and is permissive by nature.

**Comment by IntegraterGithub** [comment]
The brand

**Comment by TheOtterlord** [comment]
It's not registered, but I believe it has automatic copyright. As for trademarking the name and logo, I'm sure that will probably be done in the future

**Comment by nfitzen** [comment]
This issue is closed, but I thought I'd offer some input. As someone who isn't a lawyer but is (or claims to be) somewhat knowledgeable about copyright, this is a little bit of a pet peeve of mine.

1. Per the Berne Convention and other international copyright treaties, all creative works automatically have copyright vested in the author. If someone doesn't have a copyright license on their work, this means you cannot do _anything_ with the work outside of limitations to copyright such as fair use or exhaustion.
2. In order for something to be "not copyrighted," it has to be in the public domain. For something to be in the public domain, people have to specifically waive their copyright (using something like [CC0]). In some jurisdictions, the public domain doesn't even exist (which is why CC0 adds a fallback license). Thus, most works should be assumed not to be in the public domain.
3. A copyright license, even a permissive one, is a conferral of monopoly power to a licensee (which, in the case of most free software projects, is the general public), and specifies what the licensee can do with the copyrighted work. Most free software projects (e.g., ones licensed under the GNU GPL or the MIT/Expat license) fall under this category. These works are still copyrighted; it's just that, if a member of the public exercises a power that would ordinarily be monopolized by the copyright holder, then they may only do so under the terms of the license. (Specific license agreements can also be negotiated with copyright holders, obviously.)

I hope this clears some things up.

As for DogeHouse, like many free software projects, it's copyrighted by the respective contributors, and each contribution is licensed under the project's license (in this case Expat/MIT). You can view the copyright license under which you're permitted to use the work in the [`LICENSE` file](https://github.com/benawad/dogehouse/blob/staging/LICENSE), and, in the case of MIT/Expat, the license also contains the copyright notice, which lists all of the copyright holders of the work and the year it's published (which is a relic from when legislatures didn't practically eradicate the public domain). Currently it's "Copyright (C) 2021 Ben Awad and the DogeHouse contributors."

(Edit: obligatory IANAL, this is not legal advice disclaimer here.)

[CC0]: https://creativecommons.org/publicdomain/zero/1.0/
