### ISSUE TITLE
Language messed up.

### ISSUE THREAD

**Issue by shoury2021** [benawad/dogehouse#2223]
**Describe the bug**
When selecting a new language, not all of the content is in that language. (Eg.: "Your Feed")

**To Reproduce**
1. Select new language (not English)
2. See, that many things are still in English. (Which aren't supposed to be)

**Expected behavior**
Everything is supposed to be in the selected language.

**Screenshots**
![dogehouse-language-error](https://user-images.githubusercontent.com/82206515/115543709-35b5da00-a291-11eb-8e7d-c9716dd4880b.png)

**What device are you on?**
OS: MacOS Big Sur
Device: Macbook Pro M1 (2021)
Browser: Safari

**Additional context**
Maybe add translate feature for messages, room names, etc. for some content.

**Comment by TheOtterlord** [comment]
Not all of the translation keys have been added. If you wish to contribute, please see [the translation files](https://github.com/benawad/dogehouse/tree/staging/kibbeh/public/locales) to make your changes and submit a [pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) to get them added.

As for a translations feature, please make a seperate issue as a [feature request](https://github.com/benawad/dogehouse/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=), though I imagine something like this would be implemented later rather than sooner.
