### ISSUE TITLE
You can send blank messages using a mongolian vowel separator

### ISSUE THREAD

**Issue by Bqleine** [benawad/dogehouse#2234]
**Describe the bug**
You can send blank messages using a mongolian vowel separator

**To Reproduce**
1. Go to 'chat'
2. Click on 'send a message'
3. Enter the mongolian vowel separator : `᠎` (U+180E)
4. The message is sent

**Expected behavior**
No message is sent

**Screenshots**
![image](https://user-images.githubusercontent.com/51089082/115616156-23b75400-a2f0-11eb-94f6-c6f9573fe1f2.png)

**What device are you on?**
Web app on firefox

**Comment by Bqleine** [comment]
*Additional context*
I tried other spaces from [this list](http://jkorpela.fi/chars/spaces.html) but they didnt work

**Comment by saihnii4** [comment]
the mongolian vowel seperator's role in mongolian script is that it determines the value of the last two characters of a word. however, i believe it's rarely used in practice.

**Comment by A-Yamout** [comment]
I do not believe that this should be removed because people who are speaking Mongolian in chat might need it.

**Comment by saihnii4** [comment]
like I mentioned earlier, many Mongolians rarely use this vowel separator, and most often they resort to english/cyrillic characters to form words. however it does have an practical use in the language.
for example:

ᠬᠠᠷᠠ is not the same as ᠬᠠᠷ᠎ᠠ because the vowel at the end is disconnected, which leads to a completely different meaning

**Comment by Bqleine** [comment]
It shouldn't be removed, just checked if sent alone
