### ISSUE TITLE
Change branch from master to main. This is more inclusive and equal.

### ISSUE THREAD

**Issue by samarmohan** [benawad/dogehouse#231]

**Comment by nadirabbas** [comment]
What exactly do you mean by "inclusive and equal"?

**Comment by ridarf** [comment]
Main and master are synonymous in this context.

**Comment by samarmohan** [comment]
Do you guys not understand? Master refers to slavery. Main is better.

**Comment by samarmohan** [comment]
https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/
https://www.techrepublic.com/article/github-to-replace-master-with-main-starting-in-october-what-developers-need-to-know/
https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/

**Comment by ridarf** [comment]
While it's great that GitHub decided to make a change to feel more inclusive, the intent you're implying was not intended by GitHub or the repository owners in this context. 

Watering down serious issues like slavery with negligible "solutions" like this is quite harmful to the main cause, pulling attention away from actual slavery and relevant issues, as well as pulling attention away of the potential aftermath of historical slavery. 

Your time would be better spent actually making a difference or raising awareness elsewhere rather than going repository to repository to put on a façade of activism, evident by the fact that 40% of your own repositories still have the primary branch named "master."

This issue should be closed.

**Comment by samarmohan** [comment]
I'm working on changing my own repos. That's why I brought this up. I am _not_ closing this issue no matter what you think. Master should not be used.

**Comment by ridarf** [comment]
I'm not against changing the master branch's name to main by any means, I just think that it's a little hypocritical for you to be going on a bunch of repositories for weeks now telling them to change their branch names when you haven't even done so yourself. 

I love the change by GitHub, because it reflects progression from the platform as a whole, but going repository to repository to hunt down master branches isn't having the societal impact I think you think it does, and your time would be better spent doing something more meaningful. That's just my takeaway, anyways.

I doubt @benawad is going to have any problem with changing the name of the branch.

**Comment by samarmohan** [comment]
Ok, I am sorry. I am not hunting repos with a branch name with master. I have contributed to this repo and opened quite a few issues. And yes, all my branches should be main before I do this. I am working on that.
