### ISSUE TITLE
Mobile UX Show more follow button issue

### ISSUE THREAD

**Issue by s3ansh33p** [benawad/dogehouse#2485]
**Describe the bug**
On mobile, whilst in a room and viewing a user's followers, the room overlay is placed over the show more button. This makes it hard to click the show more button instead of the overlay.

**To Reproduce**
1. (whilst in a room) Go to my profile - https://dogehouse.tv/u/admin
2. Click on followers
3. Scroll down to the show more button

**Expected behavior**
The room overlay should be above the show more button.

**Screenshots**
https://ibb.co/NLPtNSm

**What device are you on?**
iPhone XS, Chrome

**Additional context**
N/A

**Comment by ajmnz** [comment]
I think it could be solved either by adding a bigger margin at the bottom of the list, or by changing the button to infinite scroll

**Comment by wes337** [comment]
@ajmnz Maybe even both? Because you could get to the bottom of the infinite scroll and the room badge would still be on top of the last user.

![image](https://user-images.githubusercontent.com/9464690/116811793-e5bdf980-ab53-11eb-9511-ce32a726a043.png)

Also somewhat related --- having a long name will cause the "Follow" button to be pushed off screen.

**Comment by ajmnz** [comment]
> @ajmnz Maybe even both? Because you could get to the bottom of the infinite scroll and the room badge would still be on top of the last user.

Yep, makes sense.


> Also somewhat related --- having a long name will cause the "Follow" button to be pushed off screen.

Mobile version is kinda temp, we're currently refactoring it completely to match Figma. So yeah, many things need to be polished
