### ISSUE TITLE
Twitter banner URLs are marked "Invalid Image" on Edit Profile modal

### ISSUE THREAD

**Issue by robcortez** [benawad/dogehouse#2721]
**Describe the bug**
When authenticating via Twitter, the banner URL can be valid yet marked as invalid by the UI. 

Creating an account with a Twitter login auto-populates your profile (avatar, banner, display name, and bio). All images display correctly and are legit URLs. However, the regex for the banner image in does not seem to match due to the URL not having an extension.

Here is my valid banner image URL: 
https://pbs.twimg.com/profile_banners/1241894903472427015/1587079476

**To Reproduce**

1. Create a new account by authenticating via Twitter
2. Navigate to the edit profile screen
3. Try to change Display Name, Username, or Bio
4. Click Save

**Expected behavior**
User should be able to edit other profile fields _without_ changing the auto-populated avatar and banner image fields. 

**Screenshots**
![Screenshot](https://i.imgur.com/41NXMHs.png)

**What device are you on?**
MacOS Mojave, Firefox 88.0

**Additional context**
N/A

**Comment by firecraftgaming** [comment]
Hi, this should not be a problem because it validates links that have https://pbs.twimg.com/profile_banners/x/x/x where the last x is either a size like "500x500" or a preset size like "web" and in your line you only provided the first two and not the size. Solution: put in your banner url and add a "/" and an size like "web", here is the link to twitter banner url format https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/user-profile-images-and-banners
