### ISSUE TITLE
Make @mentions convert to lowercase automatically

### ISSUE THREAD

**Issue by s3ansh33p** [benawad/dogehouse#328]
@john can be mentioned but @John doesn't work (e.g. copypasted). Make the parsing convert to lowercase after the "@" and maybe use "\" in fron of an "@" in case the user doesn't want it converted.

**Comment by nadirabbas** [comment]
Can't reproduce. I tried copy-pasting, it worked.

**Comment by nadirabbas** [comment]
Can't reproduce

**Comment by s3ansh33p** [comment]
Github auto changed Capital J to lowercase I was trying to say \@ John

**Comment by nadirabbas** [comment]
I copied uppercase, and then pasted, it worked.

**Comment by s3ansh33p** [comment]
Try typing "@nadirabbas test" and change the n to a capital n, copy/paste it and it won't convert it.

**Comment by nadirabbas** [comment]
Yeah, that is intended, because you haven't actually selected a username, there is a space after that username so the popup won't open. So it is selected when you start typing it and a popup appears, and you hit enter on one of those options.

So if you copy an uppercase or lowercase, as long as there is nothing after the username (space, etc), the popup will open, and has nothing to do with case.
