### ISSUE TITLE
Schedule for alarm chat. 

### ISSUE THREAD

**Issue by Pasit-pat** [benawad/dogehouse#344]
When I have time slot for chat in doge house. I want to schedule another people for fanclub.

**Comment by benawad** [comment]
What?

**Comment by nadirabbas** [comment]
@benawad MY interpretation of this issue:
- When is he going to have the ability to schedule rooms in Dogehouse
    So he can create a room for later
- He wants to send "alarms" (notifications) to people that subscribed to his room. Like you set a reminder on YouTube and get a notification when that premiere/stream starts.

This issue is probably Google translated from his native lang.
