### ISSUE TITLE
We have horizontal scrolling in chat

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#445]
only in case of links

![image](https://user-images.githubusercontent.com/38838675/109382609-4ede8200-7903-11eb-830b-d1ba22ce2094.png)

**Comment by nadirabbas** [comment]
This is because we have `break-words` instead of `break-all` in chat message classes. If we change it to `break-all`, then the words get broken from in between.

So lets add `break-words` in case of messages, and `break-all` in case of a link.

**Comment by nadirabbas** [comment]
@benawad some guy recommended `word-break: anywhere`. I didn't even know this was a thing.

**Comment by lenilsondc** [comment]
`word-break: anywhere` works but has some browser support limitations.

![image](https://user-images.githubusercontent.com/13702123/109395554-ba2c5200-790b-11eb-9d42-7fc7187adda4.png)

Using the `break-all` class should suffice though.

**Comment by nadirabbas** [comment]
@leonyanagida but that makes the chat undreadable. You can try locally.

**Comment by lenilsondc** [comment]
@nadirabbas I just did some testings and `overflow-wrap: anywhere` doesn't provide the desired result as well because it's going to needlessly break words that shouldn't be broken.

It turns out the class `break-words` works just fine if you add width limit along side with `max-w-full`, tested locally and seems to somewhat "fix" it.

![image](https://user-images.githubusercontent.com/13702123/109396947-ded7f800-7912-11eb-9760-b37a9b96e319.png)

**Comment by nadirabbas** [comment]
@lenilsondc Kudos! what about a PR?
