### ISSUE TITLE
Blank space in the emoji picker modal

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#529]
![image](https://user-images.githubusercontent.com/70035508/109543103-f1595980-7aeb-11eb-8a2b-3e3bad2ff68a.png)
@nadirabbas

**Comment by lenilsondc** [comment]
This is due to the height of the picker being set through style (`height: "400px", `), the container gets the height but inner wrapper doesn't follow the same height.

https://github.com/benawad/dogehouse/blob/2e909332cd3016763adc097bb02c18ef6c182935/kofta/src/vscode-webview/modules/room-chat/RoomChatInput.tsx#L136-L146

This is fixable by removing the hard coded height value and let the default value used by the picker which is somewhat around `300px`, which ain't that bad.

![image](https://user-images.githubusercontent.com/13702123/109863166-12cb5a00-7c40-11eb-97ec-8645ef09db51.png)
