### ISSUE TITLE
Replace material UI datetime picker with something better

### ISSUE THREAD

**Issue by benawad** [benawad/dogehouse#552]

**Comment by benawad** [comment]
https://github.com/benawad/dogehouse/blob/staging/kofta/src/vscode-webview/modules/scheduled-rooms/ScheduleRoomModal.tsx#L114

**Comment by michaelphipps** [comment]
My personal favourite date picker is https://flatpickr.js.org/ 
It has a very good user experience and works very well on desktop AND mobile.

HOWEVER, I think dropping date/time pickers and using a dd / mm / yyyy masked field can be a simpler experience.

**Comment by tuminzee** [comment]
This might help 
https://akveo.github.io/nebular/docs/components/datepicker/overview#nbdatepickerdirective

![image](https://user-images.githubusercontent.com/58180803/110235731-a9a55880-7f57-11eb-91e1-9ac0de10745b.png)
![image](https://user-images.githubusercontent.com/58180803/110235742-b45fed80-7f57-11eb-9a8b-78b0015f0306.png)

**Comment by SuperSonicHub1** [comment]
What's wrong with [`<input type="date">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) and [`<input type="time">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time)? In a perfect world, all browsers would support [`<input type="datetime-local">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local), but Firefox currently doesn't, so that sucks.

**Comment by michaelphipps** [comment]
@SuperSonicHub1 those fields don't render well in Chrome on my Android device.  They're ok in Firefox.

**Comment by SuperSonicHub1** [comment]
@michaelphipps Really? On Android, `<input type="date">` should use Android's native date picker. It works just fine for me on my Pixel 3a in both Firefox and Chrome in Android 11; what version of Android and Chrome are you using? 

I think that HTML5 inputs are the way to go so that choosing a date feels as native as possible, especially when dealing with mobile users. Plus, I  think it would be in the front end's best interest if it didn't have *yet another* dependency that had to be bundled.

**Comment by michaelphipps** [comment]
@SuperSonicHub1  The date input in Chrome renders like an empty drop down box for me.  Without a label it isn't clear what it is for.  When you click on it, the native widget appears as you would expect.  

Chrome version 89.0.4389.86
Galaxy S10e SM-G970F
Android 11 Build RP1A.200720.012.G970FXXS9EUB1

In firefox on the same device, the date input renders like a drop down box that has "dd / mm / yyyy".  When you click on it, the native widget appears.

My bias is toward entering dates without the widget.  Small screen + big hands + bad eyes means it bugs me when I have to mess with the widget to select a date.  I prefer the number pad keyboard because it is easier to see and I'll hit the right numbers first go.

Anyway, ultimately I agree with you.  Using `<input type="date">` and `<input type="time">` is the "right" choice.

**Comment by SuperSonicHub1** [comment]
@michaelphipps What a nasty bug. If you have the time to report it, bring it to the attention of the Chromium team: https://bugs.chromium.org/p/chromium/issues/list

But yeah, HTML5 inputs are the way to go.

**Comment by Lunchb0ne** [comment]
Yeah, this kinda allows it to have "device-specific" date pickers. But some android skins like OneUI skin that too, which causes that usability issue.

**Comment by t1m4lc** [comment]
Maybe it will be useful :  https://tailwindcomponents.com/component/datepicker-with-tailwindcss-and-alpinejs

**Comment by michaelphipps** [comment]
> Yeah, this kinda allows it to have "device-specific" date pickers. But some android skins like OneUI skin that too, which causes that usability issue.

@Lunchb0ne yep - OneUI skin is the culprit

**Comment by SuperSonicHub1** [comment]
@michaelphipps Huh; I've never used a Samsung device with OneUI before, so I didn't know that was even a thing; sounds like an issue Samsung should fix, but I doubt they will. If you can bother to do so, I wonder if these same glitches will show up if you use Samsung Internet.

**Comment by gcavanunez** [comment]
How about this one?
https://use-lilius.vercel.app/?path=/story/datepicker-multi-select--page
https://github.com/its-danny/use-lilius

**Comment by TheOtterlord** [comment]
Closed as Kofta is deprecated. Feel free to reopen if this also affects Kibbeh
