### ISSUE TITLE
Record sessions

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#578]
Since we discussed this in the weekly contributor meeting I thought This should have a feature request

**Comment by shmuelhizmi** [comment]
if #585 will pass support for audio recording will be added

**Comment by benawad** [comment]
0. I think we want to do the recording server side, MediaRecorder doesn't support iOS Safari https://caniuse.com/mediarecorder (this also needs to be thought out of how it works with deploys so a recording is not interrupted)
1. Only the creator of the room can initiate a recording
2. All current speakers need to confirm they are ok with it being recorded
3. It should be obvious to everyone in the room its being recorded and when someone joins to speak they should be prompted to confirm they are ok with this
4. The recording will be saved to Google Cloud probably
5. The recording will show up on the profile of everyone who spoke and the creator of the room can set the privacy of it to public/private (if set to private can the other speakers still see it??)

**Comment by JammSpread** [comment]
What if it can be configured that speakers who don't decide to be recorded are not recorded?

**Comment by shmuelhizmi** [comment]
I think taking in consideration doge-house user demographic, user will have no problem just using their PC to record the session and so being able to record the session directly from the app is just a matter of convenience, therefore preventing users from recording other users without thier consent isn't a matter of security but a matter responsibility (you don't want users to use your app feature to record users other users without indication that they are being recorded), taking that in consideration I want to propose a simpler solution that is much easier to implement, require less overhead from the users but is also just as responsible.

The solution is just showing a red dot below the user that is recording, (and maybe also send a message is the chat that the user has start recording) this will late all user understand that they are being recorded, and let moderators who think that the user should not be allowed to record the session kick him out.


As for cloud recording even though this can have lots of cool benefits, this will give us lots of troubles, cloud recording is complicated and that is way companies like zoom defaults to local recording ,zoom cloud recording require up to 72 hours of processing and is only available for paid users, this will not be the case with as since we only work with audio but still cloud recording is much more resource demanding compering to a regular media-server.

**Comment by benawad** [comment]
Cloud recording is more complex, but needed for this project. One of the goals of the project is to be a platform podcasters can host their podcasts on.

**Comment by ubrg** [comment]
@benawad 

Would you like to do a session record of the audio-only, or something similar to what Twitch does with its replay feature (video + chat + maybe other stuff... are replayed as if it was the actual session)?

The Twitch-like option could add some interesting features (real-time chat, speakers volume/mute... basically all features available in the actual session). However, it is much more complex than recording only the audio.

**Comment by cdbattags** [comment]
I think we can start [here](https://github.com/ethand91/mediasoup3-record-demo) as an example?

https://github.com/ethand91/mediasoup3-record-demo
