### ISSUE TITLE
X-Overlfow on Mobile

### ISSUE THREAD

**Issue by highdox** [benawad/dogehouse#87]
Where: 
Landingpage

Behavior:
User is able to scroll along the x axis.

Expected Behavior:
User is only able to scroll along the y axis.

Device: iPhone XS
Browser: Google Chrome

**Comment by Mito9999** [comment]
Hmm, I can't seem to replicate this bug. Could you please share a screenshot of the overflow?

**Comment by highdox** [comment]
Very weird, can't replicate it anymore. But I saw another visual bug when I tried: ![image](https://user-images.githubusercontent.com/49474412/107831937-7d9b1b00-6d8f-11eb-9f6a-5aed9fb902c4.jpeg)

**Comment by highdox** [comment]
Very weird, can't replicate it anymore. But I saw another visual bug when I tried: ![image](https://user-images.githubusercontent.com/49474412/107832081-cbb01e80-6d8f-11eb-9628-ff0097b70205.jpeg)

**Comment by muttenzer** [comment]
Since this issue isn't closed yet, I found the cause of the horizontal overflow. This bug was linked to the problem with too long room names. As soon as you created a room with a name over x characters, the mobile overflow appeared: ![image](https://user-images.githubusercontent.com/49474412/108635014-18c17e00-747d-11eb-80e6-7dc423b66f7a.jpeg)

**Comment by andrewrobles** [comment]
Is this still an issue? Tried recreating the bug and it looks like it may have already been taken care of (see screenshot)
<img width="376" alt="Screen Shot 2021-03-13 at 7 03 46 AM" src="https://user-images.githubusercontent.com/70864612/111034404-548b9b80-83ca-11eb-8b5d-e54622e0ac1b.png">

**Comment by goldyydev** [comment]
This has been already fixed.
