### ISSUE TITLE
I can't login anymore

### ISSUE THREAD

**Issue by dhanielcodes** [benawad/dogehouse#88]

**Comment by takashi1kun** [comment]
Same, it also kicked me out of the room i was talking

**Comment by McFranko** [comment]
Happened to me as well, it seems like api.dogehouse.tv is down

**Comment by TSMMark** [comment]
App is down. Got kicked out of the room i was in and can't sign back in. Only the login screen seems to load. Related: #89

**Comment by SturmEnte** [comment]
I also got kicked out and now i cant login anymore

**Comment by Mipsters** [comment]
same, Image for reference:
![image](https://user-images.githubusercontent.com/4920832/107834884-497c2600-6da0-11eb-9154-bfe0ed70c78b.png)

**Comment by takashi1kun** [comment]
related: https://github.com/benawad/dogehouse/issues/90

**Comment by ChrisAdels** [comment]
it was such a nice talk 🙈

**Comment by SturmEnte** [comment]
Do you have Discord? If yes, here is my Discord: SturmEnte#4367  Gesendet von Mail für Windows 10 Von: ChrisGesendet: Samstag, 13. Februar 2021 01:09An: benawad/dogehouseCc: SturmEnte; CommentBetreff: Re: [benawad/dogehouse] I can't login anymore (#88) it was such a nice talk 🙈—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Salman2301** [comment]
We back
https://dogehouse.tv/room/06c53a8a-1af0-497a-846b-3ee1eb3586be
